export default {
  check: require('./ic-check.svg'),
  closeFill: require('./ic-close-fill.svg'),
  arrowLeft: require('./ic-arrow-left.svg'),
  eyeLine: require('./ic-eye-line.svg'),
  eyeOffLine: require('./ic-eye-off-line.svg'),
  facebook: require('./ic-facebook.svg'),
  google: require('./ic-google.svg'),
  twitter: require('./ic-twitter.svg'),
  uncheck: require('./ic-uncheck.svg'),
  logo: require('./ic-logo.svg'),
  history: require('./ic-history.svg'),
  pencil: require('./ic-pencil.svg'),
  security: require('./ic-security.svg'),
  user: require('./ic-user.svg'),
  updateEmail: require('./ic-change-email.svg'),
};
